# Generated by Django 5.0.4 on 2024-04-13 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hobby_clubs", "0007_remove_club_unique_identifier_alter_club_age_like"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={},
        ),
        migrations.RenameField(
            model_name="review",
            old_name="date_added",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="review",
            name="date_modified",
        ),
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="review",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hobby_clubs.club"
            ),
        ),
        migrations.DeleteModel(
            name="Rating",
        ),
    ]
