# Generated by Django 5.0.4 on 2024-04-13 23:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hobby_clubs", "0008_alter_review_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="my_review",
            new_name="content",
        ),
    ]
